
name: swift-figma-export
options:
  bundleIdPrefix: com.myapp.figma-export
packages:
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    from: 2.7.1
targets:
  swift-figma-export:
    type: application
    platform: iOS
    deploymentTarget: "9.0"
    sources: [swift-figma-export]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
